---
title: "Funções úteis"
output: html_notebook
---

# Funções básicas e utilidades
```{r}
library(help = "base")
library(help = "utils")
```

# Local de Trabalho

Funções úteis principalmente quando estamos rodando scripts fora de um projeto. Dentro de projetos o diretório de trabalho (wd) é o local do projeto.
```{r}
getwd()
setwd("C:/Users/Trabalho/Documents/GitHub/aulas-r-grabriel")
```

# Gerenciar Pacotes
```{r}

install.packages()
installed.packages()
update.packages()

library(psych)
require(psych) # Para uso dentro de funções, gera warning quando o pacote não existe
psych::corr.test()

# Descarregar pacotes:
unloadNamespace(psych) # pode ser útil se tiverem dois pacotes com funções de mesmo nome
```

# Ajuda

```{r}
help(topic = corr.test, package = psych)
help(corr.test)
?corr.test
```

# Leitura de dados

```{r}
read.csv()
read.csv2()
read.delim()

library(foreign)
read.spss()
read.ssd()

library(xlsx)
read.xlsx()
read.xlsx2()
```

# Mudar dados

```{r as.}
as.data.frame()
as.matrix()
as.character()
as.factor()
as.numeric()
as.Date()
as.POSIXct()
```

## Dados nativos

```{r}
saveRDS()
```


